### ISSUE TITLE
GenerateNextCreditCardNumber does not work as expected

### ISSUE THREAD

**Issue by intrueder** [Nick-Knock/All_Tasks#3]
Test:

``` cs
GenerateNextCreditCardNumber("343434343434343")
```

Expected: `"343434343434350"`
But was:  `"343434343434353"` (neither **next** nor **valid** card number was generated)

**Comment by Nick-Knock** [comment]
Already fixed these bugs. Link to the repository with update code source.
https://github.com/Nick-Knock/All_Tasks.git
