### ISSUE TITLE
GetCreditCardVendor method does not work as expected

### ISSUE THREAD

**Issue by intrueder** [Nick-Knock/All_Tasks#5]
Pass `34343434343434300` to `GetCreditCardVendor` method
Expected result: "Unknown" (17 digits card number is too long for AmericanExpress)
Actual result: "AmericanExpress"

**Comment by Nick-Knock** [comment]
Have fixed this bug. Here link to an update repository.
https://github.com/Nick-Knock/All_Tasks.git
